services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: fastapi run src/app/main.py --host 0.0.0.0 --port 8000
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/events || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
    develop:
      watch:
        # only sync source code & main script
        - action: sync
          path: ./backend/src/app
          target: /app/src/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: [uv, run, streamlit, run, Home.py]
    ports:
      - 80:8501
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - ./frontend/assets:/app/assets
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    develop:
      watch:
        - action: sync
          path: ./frontend/Home.py
          target: /app/Home.py
        - action: sync
          path: ./frontend/pages
          target: /app/pages
        - action: sync
          path: ./frontend/utils
          target: /app/utils

networks:
  default:
    driver: bridge
