name: Kanta Backend CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/src/**'
      - 'backend/pyproject.toml'
      - 'backend/uv.lock'

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        working-directory: ./backend
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff linting
        working-directory: ./backend
        run: uvx ruff check --fix

      - name: Run tests
        working-directory: ./backend
        run: uv run pytest tests