name: Kanta Face Clustering CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'cluster-faces/src/**'
      - 'cluster-faces/tests/**'
      - 'cluster-faces/pyproject.toml'
      - 'cluster-faces/uv.lock'

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run Ruff linting
        working-directory: ./cluster-faces
        run: uvx ruff check --fix

      - name: Install the project
        working-directory: ./cluster-faces
        run: uv sync --locked --all-extras --dev

      - name: Check for src changes
        id: check-src-changes
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only FETCH_HEAD HEAD)
          if echo "$CHANGED_FILES" | grep -q "cluster-faces/src/"; then
            echo "src_changed=true" >> $GITHUB_OUTPUT
          else
            echo "src_changed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Run tests
        working-directory: ./cluster-faces
        if: steps.check-src-changes.outputs.src_changed == 'true'
        run: uv run pytest tests