name: Kanta Face Clustering CI

on:
  push:
    branches: [ main ]
    paths:
      - 'cluster-faces/src/**'
      - 'cluster-faces/tests/**'
      - 'cluster-faces/pyproject.toml'
      - 'cluster-faces/uv.lock'
  pull_request:
    branches: [ main ]
    paths:
      - 'cluster-faces/src/**'
      - 'cluster-faces/tests/**'
      - 'cluster-faces/pyproject.toml'
      - 'cluster-faces/uv.lock'

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        working-directory: ./cluster-faces
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff linting
        working-directory: ./cluster-faces
        run: uvx ruff

      - name: Run tests
        working-directory: ./cluster-faces
        if: ${{ github.event_name == 'push' && contains(github.event.commits[0].modified, 'cluster-faces/src/') || github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'cluster-faces/src/') }}
        run: uv run pytest tests