name: Kanta Face Clustering CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff linting
        run: uvx ruff

      - name: Run tests
        if: ${{ github.event_name == 'push' && contains(github.event.commits[0].modified, 'src/') || github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'src/') }}
        run: uv run pytest tests